M48
; DRILL file KiCad 10.0.3 date 2026-06-09T20:37:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-09T20:37:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X162.685Y-69.68
X167.535Y-69.68
T2
X162.385Y-66.65
X167.835Y-66.65
T3
X134.5Y-67.0
X135.0Y-109.0
X181.0Y-67.0
X181.0Y-117.5
M30
